name: Prepare Release Build & PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        type: string
        required: true

jobs:
  run_tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Run tests
      shell: bash
      run: sh mock_test_cases.sh

  prepare_release_branch:
    name: Prepare release branch
    needs: [ run_tests ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Install JQ, specific to this repo
      shell: bash
      run: sudo apt-get install jq
    - name: Version number validation
      shell: bash
      run: ruby ./version_validation.rb ${{ github.event.inputs.version }}
    - name: Update translations
      shell: bash
      run: sh ./update_translation.sh ${{ github.event.inputs.version }}
    - name: Update build
      shell: bash
      run: sh ./update_build.sh ${{ github.event.inputs.version }}
    - name: Create relase branch
      uses: EndBug/add-and-commit@v9
      with:
        message: Updated translation & uploaded build
        committer_name: GitHub Actions
        committer_email: actions@github.com
        new_branch: 'release-${{ github.event.inputs.version }}'
    
  create_pr:
    name: Create PR to main from release branch
    runs-on: ubuntu-latest
    needs: [ prepare_release_branch ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: 'release-${{ github.event.inputs.version }}'
    - name: test
      shell: bash
      run: sh ./update_build.sh 1.0.0 && cat mock_build.json
    # - name: Create Pull Request
    #   id: cpr
    #   uses: peter-evans/create-pull-request@v4
    #   with:
    #     branch: 'release-${{ github.event.inputs.version }}'
    #     base: main
    #     title: 'Release Version:${{ github.event.inputs.version }}'